myself:
  gwId: FEFEABABABFE
  gwIP: 192.168.0.102
  serverIP: 192.168.0.254
  serverPort: "8286"
  dataUpCycle: 10
  heartCycle: 15
  dataReadCycle: 60
websocket:
  path: /
rf:
  id: ACACACACACAC
  channel: "1"
  netId: BEBEBEBEBEBE
